ALTER TABLE users ADD COLUMN IF NOT EXISTS role_global TEXT NOT NULL DEFAULT 'user';
ALTER TABLE users ADD COLUMN IF NOT EXISTS is_active BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE businesses ADD COLUMN IF NOT EXISTS suspended BOOLEAN NOT NULL DEFAULT false;
